#!/bin/bash
echo "Age distribution:"
awk 'BEGIN{FS="\t";a=0;b=0;c=0;printf "%-15s%-10s%-10s\n","Range","Count","Percentage"}$6~/^[[:digit:]]+/{if($6<20){a++}else if ($6>30){c++}else{b++}}END{printf  "%-15s%-10d%-10.3f\n","20岁以下",a,a/NR;printf  "%-15s%-10d%-10.3f\n","[20-30]",b,b/NR;printf  "%-15s%-10d%-10.3f\n","30岁以上",c,c/NR}' worldcupplayerinfo.tsv

echo "Position:"
awk 'BEGIN{FS="\t";printf "%-15s%-10s%-10s\n","Position","Count","Percentage"}$6~/^[[:digit:]]+/{p[$5]++}END{for (i in p){printf "%-15s%-10s%-10s\n",i,p[i],p[i]/NR}}' worldcupplayerinfo.tsv

echo "Name lenth:"
max_length=$(awk 'BEGIN{FS="\t";a=0;b=300}$6~/^[[:digit:]]+/{if(length($9)>a){a=length($9)};if(length($9)<b){b=length($9)}}END{printf a}' worldcupplayerinfo.tsv)
min_length=$(awk 'BEGIN{FS="\t";a=0;b=300}$6~/^[[:digit:]]+/{if(length($9)>a){a=length($9)};if(length($9)<b){b=length($9)}}END{printf b}' worldcupplayerinfo.tsv)

awk -vmax="$max_length" 'BEGIN{FS="\t";}length($9)==max{printf "[%s] has the longest name, whose length is %d.\n",$9,length($9)}' worldcupplayerinfo.tsv
awk -vmin="$min_length" 'BEGIN{FS="\t";}length($9)==min{printf "[%s] has the shortest name, whose length is %d.\n",$9,length($9)}' worldcupplayerinfo.tsv

echo "Age:"
max_age=$(awk 'BEGIN{FS="\t";a=0;b=300}$6~/^[[:digit:]]+/{if($6>a){a=$6};if($6<b){b=$6}}END{printf a}' worldcupplayerinfo.tsv)
min_age=$(awk 'BEGIN{FS="\t";a=0;b=300}$6~/^[[:digit:]]+/{if($6>a){a=$6};if($6<b){b=$6}}END{printf b}' worldcupplayerinfo.tsv)

awk -vmax="$max_age" '$6==max{printf "The oldest player is %s, who is %s.\n",$9,$6}' worldcupplayerinfo.tsv
awk -vmin="$min_age" '$6==min{printf "The youngest player is %s, who is %s.\n",$9,$6}' worldcupplayerinfo.tsv
